packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "prisma": true
  "esbuild": true
  "@tailwindcss/oxide": true
  "vue-demi": true
  "bcrypt": true
  "unrs-resolver": true
  "@scarf/scarf": true
